version: '3.8'

services:
  database:
    container_name: mariadb
    image: mariadb:10
    ports:
      - ${DATABASE_PORT}:3306
    environment:
      MARIADB_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    restart: unless-stopped
    volumes:
      - ./.infra/mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

  server:
    container_name: go_backend
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - database
    ports:
      - 8080:8080
    env_file:
      - ./.env
    environment:
      DATABASE_URL: ${DATABASE_USER}:${DATABASE_PASS}@tcp(database:${DATABASE_PORT})/${DATABASE_NAME}?parseTime=true
    networks:
      - backend

networks:
  backend:
    driver: bridge
